version: '2'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545

  kvstore:
    build: .
    image: hcaptcha/eth-kvstore:latest
    environment:
      - ETH_HOST=ganache
      - ETH_PORT=8545
    depends_on:
      - ganache
